sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

# command to run tests
script: fastobo-validator psi-ms.obo

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis

#notifications:
#  email:
#    - psidev-ms-vocab@lists.sourceforge.net
