name: New Software Term
description: A shorthand term request for a new software term
body:
  - type: input
    id: name
    attributes:
      label: "What is the new software's name?"
      placeholder: "The new software's name"
    validations:
      required: true
  - type: textarea
    id: definition
    attributes:
      label: "Describe the software briefly."
      placeholder: "The contents of the `def` section of the new term."
  - type: dropdown
    id: software_type
    attributes:
      label: "Software type"
      multiple: true
      options:
        - MS:1000531 ! software
        - MS:1000871 ! SRM software
        - MS:1000873 ! peptide attribute calculation software
        - MS:1001139 ! quantitation software name
        - MS:1001455 ! acquisition software
        - MS:1001456 ! analysis software
        - MS:1001457 ! data processing software
        - MS:1002333 ! conversion software
        - MS:1002414 ! postprocessing software
        - MS:1002878 ! small molecule analysis software
        - MS:1002964 ! lipidomics analysis software        
        - MS:1000615 ! ProteoWizard software
        - MS:1000689 ! Agilent software
        - MS:1000690 ! SCIEX software
        - MS:1000691 ! Applied Biosystems software
        - MS:1000692 ! Bruker software
        - MS:1000693 ! Thermo Finnigan software
        - MS:1000694 ! Waters software
        - MS:1000752 ! TOPP software
        - MS:1001557 ! Shimadzu Corporation software
        - MS:1001798 ! LECO software
        - MS:1002180 ! TOPP software adaptor
        - MS:1002286 ! Trans-Proteomic Pipeline software
        - MS:1002383 ! SCiLS software
  - type: textarea
    id: extra
    attributes:
      label: "Describe any additional information."
      placeholder: "Add any additional details that might be relevant."
