name: Ask a question
description: Ask a question about the PSI-MS controlled vocabulary or related formats
body:
  - type: textarea
    id: question
    attributes:
      label: Describe the question or discussion
      placeholder: "Describe the question or discussion here."
    validations:
      required: true
