name: tag-new-version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - test-tag

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract version from OBO
        run: |
          CV_VERSION=`grep data-version psi-ms.obo | grep -oP "(\d+.\d+.\d+)"`
          echo CV_VERSION=${CV_VERSION}
          echo "CV_VERSION=${CV_VERSION}" >> $GITHUB_ENV
      - name: GitHub Tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          dry_run: true
          github_token: secrets.PSI_MS_CV_GITHUB_TOKEN
          pre_release_branches: test-tag
          custom_tag: ${{ env.CV_VERSION }}